### ISSUE TITLE
Question on connection tracking

### ISSUE THREAD

**Issue by tbarbette** [facebookincubator/katran#106]
Hi, how are TCP and UDP connections removed from the connection tracking table? I see for instance an LRU_UDP_TIMEOUT of 30 seconds. Does that mean after 30 seconds a UDP connection gets broken?
Thanks,
Tom

**Comment by udippant** [comment]
Both types of connections are stored in the connection tracking table with the underlying implementation of [per-cpu lru-cache](https://github.com/facebookincubator/katran/blob/master/katran/lib/bpf/balancer_maps.h#L43). 

As you pointed out, for UDP connections, the entries are discarded if they're idle for more than the LRU_UDP_TIMEOUT ([code](https://github.com/facebookincubator/katran/blob/master/katran/lib/bpf/balancer_kern.c#L157)). For TCP connections, there is no such explicit timeout. It is only limited by the max_size of the LRU_CACHE, after which new / recently accessed items will replace the least recently used items.

> Does that mean after 30 seconds a UDP connection gets broken?

If the connection cannot be found on the connection table (for both TCP or UDP), Katran picks the end host based on the hash of (typically) 5-tuples ([code](https://github.com/facebookincubator/katran/blob/master/katran/lib/bpf/balancer_kern.c#L119)).

**Comment by tbarbette** [comment]
Clear and limpid, thanks!
