### ISSUE TITLE
License of katran.proto

### ISSUE THREAD

**Issue by chenwng** [facebookincubator/katran#108]
Hi,

Currently katran.proto is covered by GNU license.  Based on this [https://www.gnu.org/licenses/gpl-faq.html#GPLOutput](https://www.gnu.org/licenses/gpl-faq.html#GPLOutput), 
```
when a program translates its input into some other form, the copyright status of the output inherits that of the input it was generated from.
```
I assume the generated language specific pb files are also GNU licensed. This may cause problems for people using gRPC interface to control katran.  
If my concerns are real, is it possible to change the license of this specific file to Apache/MIT like? I suppose this change won't  affect the license status of other cpp files linking against GPL libs. 

Thanks.

**Comment by fbwut** [comment]
HI @chenwng - can you elaborate on why you think this?

> This may cause problems for people using gRPC interface to control katran.

Thanks!

**Comment by chenwng** [comment]
Hi,

Thanks for the reply. My assumption is based on the link I pasted. If the katran.proto is GPL licensed, the generated pb files for different languages are also GPLed. Let's say, I have a golang based daemon and I want to add some function to control katran using the generated pb files via gRPC, I will have to license my code with GPL instead of Apache/MIT/... because golang uses static linking.

I found an archive about the license change on libbpf. They explicitly changed libbpf license to BSD-2-Clause+LGPL to avoid this. https://lore.kernel.org/patchwork/patch/996183

Anyway, I am not a layer and my assumption could be wrong. And if it was your intend to let people share their code based on the work of katran with GPL, I also respect that.

Cheers.

**Comment by tehnerd** [comment]
@syotfs ping. I'm kinda interested as well

**Comment by paullaffitte** [comment]
Fair point. I'm also interested about this matter. I'm working on a project where I might use the example gRPC server with a golang client and the question of licensing is important to us.

**Comment by tehnerd** [comment]
Cc @udippant as it seems you are looking into GitHub issues on regular basis
