### ISSUE TITLE
QUIC Header Parsing

### ISSUE THREAD

**Issue by rishabh246** [facebookincubator/katran#109]
The XDP code parses QUIC headers for any packet headed to a VIP that supports QUIC. 
It does not check if the packet's transport protocol is UDP, instead, it assumes it ([here](https://github.com/facebookincubator/katran/blob/master/katran/lib/bpf/balancer_kern.c#L520)).
Is the assumption enforced by higher layers? 
If not, this can (in theory) lead to incorrect header parsing if one was able to send a Katran instance a TCP packet destined to such a VIP.

**Comment by udippant** [comment]
@rishabh246  before trying to parse as quic header, it actually checks if the 'vip_info' has QUIC flag set @ https://github.com/facebookincubator/katran/blob/master/katran/lib/bpf/balancer_kern.c#L513. And the information about the protocol is already factored in while looking up the vip_info from the bpf map with vip meta data @ https://github.com/facebookincubator/katran/blob/master/katran/lib/bpf/balancer_kern.c#L470.

i.e. it'll try to parse for QUIC header only if the QUIC specific flag is set for the vips receiving packets.

**Comment by udippant** [comment]
Closing. Feel free to reopen if you have further questions.
