### ISSUE TITLE
How can I use config file to run katran

### ISSUE THREAD

**Issue by liuflylove666** [facebookincubator/katran#11]
if i restart katran_server then config data miss take,
if i have to two network interface Wan <--->Lan，how can i configure
like this:
client(172.16.1.100)--->Wan(eth1:172.16.1.101)(vip:172.16.1.200)<--->Lan(eth0:192.168.1.10)--->server(192.168.1.20)

**Comment by tehnerd** [comment]
right now examples only includes CLI tools which are configuring katran from cli output.
e.g. (following this guide: https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md) in you scenarion you need to start katran server.
i would assume that you want to use 172.16.1.200 as a VIP. lets say you have a TCP service running on port 80. in this scenario on katran side you need to
1) configure VIP:  ./katran_goclient -A -t 172.16.1.200:80
2) add backend server to this VIP (e.g. with address 192.168.1.20) 
 ./katran_goclient -a -t 172.16.1.200:80 -r 192.168.1.20

after this configuration every packet which katran_server would recive with dst ip 172.16.1.200 port 80 would be encapsulated inside another IP header and resend to server with IP address 192.168.1.20

server w/ ip 192.168.1.20 must have ip 172.16.1.200 assigned to loopback interface (as it would terminate tcp session. all traffic from server will go directly to client (aka katran is handling only ingress packets)

**Comment by tehnerd** [comment]
look for "Configuration of forwarding plane" section in EXAMPLE.md (link in prev reply). it shows how to configure and test your topology in greater details

**Comment by tehnerd** [comment]
Let me know if you have more/other questions

**Comment by liuflylove666** [comment]
@tehnerd  Thanks very much

**Comment by tehnerd** [comment]
I will close this for now. Feel free to open a new one if you have any new questions
