### ISSUE TITLE
How can I enable IPIP RSS on my L7 server?

### ISSUE THREAD

**Issue by takehaya** [facebookincubator/katran#111]
hi. 

https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md#configuration-of-forwarding-plane
I read the following text and do not understand, so I ask a question.
```
Interesting part here is the source of IPIP packets – that it is not equal to the source of the load balancer, but instead it's a crafted one, where first two octets are equal to 172.16 (defined in katran/lib/bpf/balancer_const.h and is configurable) in IPIP_*_PREFIX macros) and the last two are crafted in a way, that they would be the same for a single tcp flow but different flows will have different source IP. This is designed intentionally to leverage RSS capability of the NIC.
```

I don't know how to actually send the IPIP packet of the L7 server and make it RSS and then process it.

For example, there is no item to set ipip by looking at rx-flow-hash with ethtool.
https://man7.org/linux/man-pages/man8/ethtool.8.html

> rx-flow-hash tcp4|udp4|ah4|esp4|sctp4|tcp6|udp6|ah6|esp6|sctp6

If you don't mind, please let me know how I can make RSS work.

thanks.

**Comment by udippant** [comment]
@takehaya the explanation about the IPIP you linked is talking about the **source** IP in the outer IP header (that Katran adds). The destination IP in the outer IP header would be the IP address of the L7 server.

The reason we need to 'craft' the source IP with some randomized value (that is seeded with 4-tuple for connection level consistency) is that on the receiving side (L7 server), we want to distribute the packets more or less uniformly over the available rx-queues, and avoid excessive skews in any particular rx-queue. If we do not craft the value and just add the L4's source IP in the outer IP header then it'll result in skews as many flows will have the same src (L4) and dest IP (L7) address.

> I don't know how to actually send the IPIP packet of the L7 server and make it RSS and then process it.

Not sure if I understand your question. But you do not need to do any extra configuration (beyond what is mentioned in the Example doc). Katran will put the IP address of the L7 host as dst IP in the outer IP header once it picks the destination L7 host for incoming packet from the list of configured L7 servers. 

If your question is about decapsulating the packet on the L7 server, then [there's a guide in the same doc](https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md#starting-katran) on how to set the ip-tunnels for that.

**Comment by takehaya** [comment]
@udippant
Thanks for the reply!
Yes, I understand that katran randomizes src ip for the convenience of hashing. and I understand that since it is L3DSR, there is no problem with Src being randomized.

However, I don't understand why you would want IPIP RSS to work on L7 hosts.
For example, on mlx5e, there is a configuration item like this, but it appears to assume flow steering

https://github.com/torvalds/linux/commit/a795d8db2a6d3c6f80e7002dd6357e6736dad1b6

I'm wondering if I need to configure something to make RSS work.

**Comment by udippant** [comment]
Ah, I see. 

From he commit - 
https://github.com/torvalds/linux/commit/a795d8db2a6d3c6f80e7002dd6357e6736dad1b6 

> Tunneled packets with protocol numbers: 0x4 (IP-in-IP) and 0x29 (IPv6) are RSS-ed on the inner IP header. 

Looks like that patch adds support for RSS'ing based on the *inner IP* headers for IPIP - which is nice.

But even without that, drivers should RSS based on the the outer IP - which is why we randomize the src IP on the outer IP header to make the distribution uniform across rx-queues.

> I'm wondering if I need to configure something to make RSS work.

Have you tried running Katran (following the setup guide)? What do you see in term of distribution of packets on the L7 server? Do you see the RSS not being applied?

**Comment by takehaya** [comment]
I understood!

> But even without that, drivers should RSS based on the the outer IP - which is why we randomize the src IP on the outer IP header to make the distribution uniform across rx-queues.

I'm sorry. I haven't tried it yet.
I just understood that RSS will be enabled.
I didn't know about the automatic RSS activation because I searched for it and didn't find anything about it in the linux docs.

Thank you for answering my question :bow:

**Comment by udippant** [comment]
It is possible some drivers may not have this support enabled by default. Which is why I was curious if you saw such issues after running Katran.

Closing this issue. Feel free to reopen if you see such issues.

**Comment by takehaya** [comment]
Hi @udippant !
I have actually built and sent IPIP packets to mlx5e, but RSS is not enabled.
I report this.

Do you know how to solve this?

this case
* v4 only: enable
* v4/udp: enable
* v4/tcp: enable
* v4/v4: not working

i used config
```
for i in rx tx tso ufo gso gro lro tx nocache copy sg txvlan rxvlan; do
       /sbin/ethtool -K ens4f1 $i off 2>&1 > /dev/null;
done

ethtool -L ens4f1 combined $(nproc --all)
ethtool -K ens4f1 rxhash on
ethtool -K ens4f1 ntuple on

for proto in tcp4 udp4 tcp6 udp6; do
   /sbin/ethtool -N ens4f1 rx-flow-hash $proto sd
done
```
