### ISSUE TITLE
What about a version number?

### ISSUE THREAD

**Issue by paullaffitte** [facebookincubator/katran#113]
Hello,

I'm interested in using Katran to build a load-balancer, however, I don't feel very confident knowing that it's unversioned. I don't even know how to handle it. There is no changelog so I cannot know if there is a critical bug fix, or a breaking change if I use a newer version of the code.

Do you plan to release well defined versions in the future? Using [Semantic Versioning 2.0.0](https://semver.org/) seems to be a good solution as most open-source projects are following this spec.

Thanks

**Comment by udippant** [comment]
Thank you @paullaffitte  for your interest in using Katran to build an LB.

We do not have any immediate plan to implement versioning. Part of the reason has to do with the way Katran consumes its dependencies (libraries such as folly, fizz, wangle etc) which are not versioned themselves. Also our internal setup does not naturally lend itself to this manner of versioning.

We really make efforts to ensure that we do not introduce API breaking changes ourselves. If we need to do so in future, we will communicate in advance (or perhaps revisit versioning). 

However, there is still a possibility in terms of introducing incompatibility by virtue of using new features and APIs in BPF available only in newer Kernel versions, as raised in this issue https://github.com/facebookincubator/katran/issues/100.  
We try to address that by:
- making sure new features are opt-in for users
- Also, we are currently working to add a framework internally that continuously tests the code path in multiple kernel versions (we'll update the issue and the README doc once we have finalized this).

As I mentioned earlier, while we do not have immediate plan for adding explicit versioning, we will revisit this if there's a compelling need for it.
Let us know if you have further questions.

**Comment by udippant** [comment]
Closing this. Feel free to reopen if you have further questions.
