### ISSUE TITLE
About IPv6 in IPv4 encapsulation

### ISSUE THREAD

**Issue by mchtech** [facebookincubator/katran#114]
> EXAMPLE.md
> ipv6 in ipv4 encapsulation is not supported (for example you cannot have IPv6 VIP with IPv4 reals. However, you can have IPv4 VIP with IPv6 reals)

Is there a plan to support IPv6 in IPv4 encapsulation (sit mode tunnel) ?

for healthcheck 
| encap | kmod |
|---|--
|vip4-rs4| ipip -> sit❓
|vip4-rs6| ip6tnl 
|vip6-rs6| ip6tnl
|vip6-rs4| sit❓

**Comment by yangchi** [comment]
I'm not aware of such plan. @udippant

**Comment by avasylev** [comment]
There's no such plan at the moment, but we'd welcome PR.
