### ISSUE TITLE
example_grpc build fails

### ISSUE THREAD

**Issue by pvautee** [facebookincubator/katran#120]
I was going over tutorial Example.md (https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md).  for the Step where we build build the cli tool & need to run a script from example_grpc dir: ./build_grpc_client.sh.  
I got following **_error_**:
**protoc -I protos/ protos/katran.proto --go_out=plugins=grpc:goclient/src/katranc/lb_katran
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC**

looks like plugins are not supported anymore see this issue reported on protobuf repo: "https://github.com/golang/protobuf/issues/1070" 
so Could you please suggest what is equivalent option using "--go-grpc_out" for below existing protoc command line options:
#protoc -I protos/ protos/katran.proto --go_out=plugins=grpc:goclient/src/katranc/lb_katran --> NOT SUPPORTED

Another question: what go_package parameter I shall set in katran.proto file?

**Comment by WagleTanvi** [comment]
I am also facing this issue. Please advise.

**Comment by vipinpv85** [comment]
I was having a similar issue and have been facing difficulty building `example_grpc`. I used the following steps to resolve the issues 

1. Ensure all the dependencies are built via `build_katran.sh`
2. Search for `protoc-gen-go` inside the build dependency bin folder
3. set linux environment PATH to reflect the binary path for protoc-gen-go
4. set GOROOT and GOPATH
4. re-run `build_grpc_client.sh`, resolve any go dependency via `go get`
5. the protoc generate `katran.pb.go` inside ` goclient/src/katranc/lb_katran/protos/katran.proto/`
6. move the file to ` goclient/src/katranc/lb_katran/` 
7. rename `lb_katran.go`
8. re-run the `build_grpc_client.sh` , this will now build the binary in example_grpc folder.

**Comment by yaa110** [comment]
same here

**Comment by yaa110** [comment]
@vipinpv85 there is no `protoc-gen-go` inside the build dependency bin folder after running `build_katran.sh`.

**Comment by akamit** [comment]
You can install it system wide before running build_grpc_client.sh
go get -u github.com/golang/protobuf/protoc-gen-go

**Comment by udippant** [comment]
Closing. Feel free to reopen if you have still see issues or have further questions.
