### ISSUE TITLE
can katran support ingress with one Nic and egress with another Nic.

### ISSUE THREAD

**Issue by cupide1991** [facebookincubator/katran#121]
As katran described in HomePage：katran is built with the assumption that it's going to be used in a "load balancer on a stick" scenario: where single interface would be used both for traffic "from user to L4 lb (ingress)" and "from L4 lb to L7 lb (egress)."

But in my production environment，eth0 is with public ip，but eth1 is with inner ip。Ingress data comes to eth0 ，but need to do load balance with eth1。I Konw that with one nic，things would be easy，what I wonde is can I use "xdp_redirect" to make katran to support this scene（with router table and arp table obtain and updated in user space）

**Comment by udippant** [comment]
Given the specific nature of the problem, we will probably not support two interfaces in Katran anytime soon.

Perhaps you try to attach two xdp programs. On the eth0 (public) interface you can attach a simple program (see [e.g. in userspace](ttps://github.com/facebookincubator/katran/blob/master/katran/lib/BpfAdapter.cpp#L449), [simple xdp prog](https://github.com/facebookincubator/katran/blob/master/katran/lib/bpf/xdp_root.c#L31) ) that runs XDP_REDIRECT to redirect the packet to the other interface as you mentioned, and attach Katran's XDP program.

**Comment by cupide1991** [comment]
> Given the specific nature of the problem, we will probably not support two interfaces in Katran anytime soon.
> 
> Perhaps you try to attach two xdp programs. On the eth0 (public) interface you can attach a simple program (see [e.g. in userspace](https://github.com/facebookincubator/katran/blob/master/katran/lib/BpfAdapter.cpp#L449), [simple xdp prog](https://github.com/facebookincubator/katran/blob/master/katran/lib/bpf/xdp_root.c#L31) ) that runs XDP_REDIRECT to redirect the packet to the other interface as you mentioned, and attach Katran's XDP program.

If I attach a simple xdp prog to run XDP_REDIRECT on eth0(public)，I wonder whether katran's xdp prog on eth1 can detect the packets which come from eth0. Because xdp only detect packets on RX direction，XDP_REDIRECT means to TX packets from eth1???

Also I have tried in this way : attach katran‘s xdp on eth0 and change katran's XDP_TX to XDP_REDIRECT in some cases and attach a dump xdp prog on eth1，until now things look like ok.

**Comment by avasylev** [comment]
@cupide1991 if you made it work, please submit PR with instructions, interesting case, might be handy for others
