### ISSUE TITLE
Trying EXAMPLE on single server

### ISSUE THREAD

**Issue by kgs** [facebookincubator/katran#128]
Hi, 

I am trying to run https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md on one VM, trying to emulate scenario when both katran and L7 lb (nginx) is on the same host (which I understand is default for facebook also).

I would really appreciate some explanation which IP is which :) 

Let's skip health-check scenario for now and use standalone mode for katran.

Since both lb & real are on the same host then both debug scripts will be run on the same machine:

IP of machine is 10.8.192.134

```
$ ./collect_debug_lb.sh
### links ###
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:55:63:15 brd ff:ff:ff:ff:ff:ff
### default route ###
default via 10.8.192.1 dev eth0
### neighbors ###
10.8.192.1 dev eth0 lladdr 00:00:5e:00:01:5c REACHABLE
10.8.192.2 dev eth0 lladdr 8c:60:4f:79:fd:41 STALE
10.8.192.3 dev eth0 lladdr 8c:60:4f:76:38:bc STALE
10.8.192.32 dev eth0 lladdr fa:16:3e:76:f3:c0 STALE
### ps ###
 4108 pts/1    R+     0:00 grep katran
### sysctl ###
net.core.bpf_jit_enable = 1
net.core.bpf_jit_harden = 1
net.core.bpf_jit_kallsyms = 0
```

```
$ ./collect_debug_real.sh
### links ###
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:55:63:15 brd ff:ff:ff:ff:ff:ff
### default route ###
default via 10.8.192.1 dev eth0
### neighbors ###
10.8.192.1 dev eth0 lladdr 00:00:5e:00:01:5c REACHABLE
10.8.192.2 dev eth0 lladdr 8c:60:4f:79:fd:41 STALE
10.8.192.3 dev eth0 lladdr 8c:60:4f:76:38:bc STALE
10.8.192.32 dev eth0 lladdr fa:16:3e:76:f3:c0 STALE
### sysctl ###
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.arp_filter = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.eth0.arp_filter = 0
net.ipv4.conf.eth0.rp_filter = 1
net.ipv4.conf.lo.arp_filter = 0
net.ipv4.conf.lo.rp_filter = 0
### iptables ###
Chain INPUT (policy ACCEPT 613 packets, 61554 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 668 packets, 1309K bytes)
 pkts bytes target     prot opt in     out     source               destination
```
This is before any changes made.

So, my steps should be as follows (based on https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md#configuration-of-forwarding-plane):

1. Minimal setup
```
$ sudo sysctl net.core.bpf_jit_enable=1
$ sudo tc qd add  dev eth0 clsact

$ sudo ip link add name ipip0 type ipip external
$ sudo ip link add name ipip60 type ip6tnl external
$ sudo ip link set up dev ipip0
$ sudo ip link set up dev ipip60

$ sudo ip a a 127.0.0.42/32 dev ipip0

$ for sc in $(sysctl -a | awk '/\.rp_filter/ {print $1}'); do  echo $sc ; sudo sysctl ${sc}=0; done
```
2. Adding VIP for the REAL (which is this machine).
```
$ sudo ip a a 10.200.200.1/32 dev lo
```
And **first** question here, why it is on "lo" interface, is it because it simply must be defined somewhere on REAL host for DSR to work?

3. Starting Katran (am I using correct MAC here?):
```
 sudo ./build/example_grpc/katran_server_grpc -balancer_prog ./deps/bpfprog/bpf/balancer_kern.o -default_mac  00:00:5e:00:01:5c -hc_forwarding=false -intf=eth0 -lru_size=10000
```

3. Configuring Katran (LB part, we are using port 8080)
```
./katran_goclient -A -t 10.200.200.1:8080
./katran_goclient -a -t 10.200.200.1:8080 -r 10.8.192.134
```
**Second** question here, I am using 10.8.192.134 as REAL IP since this is the IP configured for this machine on eth0 and here I will be listening with Nginx on 8080 port.

Btw, I do not exactly get what is the meaning of `10.0.0.2` IP in original EXAMPLE, is it some external IP for real server?

4. Aaand, that's it?

And now, how to test it? Nobody outside this machine knows that VIP 10.200.200.1 is handled on machine previously known under 10.8.192.134 only - should I create some static route to it?

Also, how is connection with tunneling interfaces (ipip) configured? Does Katran use it by default without any extra effort needed here?

Thanks in advance for any help!

**Comment by udippant** [comment]
Let us know if you have further questions.
