### ISSUE TITLE
Use case for healtcheck forwarding

### ISSUE THREAD

**Issue by kgs** [facebookincubator/katran#132]
Hi, what is use case for https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md#configuring-healthchecks-forwarding ??

As I understand, if I want to add or remove reals from VIP I can run some script on LB itself which will be calling real by it's IP and then will modify reals list accordingly (via grpc API for example). Will this not work? What is advantage here of using forwarding?

**Comment by udippant** [comment]
"Forwarding" here mean targeting individual servers for the vip (i.e. reals) with healthcheck request - which'll need to be encapsulated.
Use case: in a typical DSR setup, it is common for the L4 layer (e.g. control plane around Katran) to regularly healthcheck the backend servers (reals) for each VIP. To do so, it needs to encapsulate the healthcheck packets where the outer IP has the IP of the reals while the inner packet has the IP of the VIP itself. The advantage of such setup is that it not only ensures the real server is UP and running but also ensures the real is actually serving the VIP (hence the dst IP in the inner packet). For example if the application (say a proxy) serving the VIP on that real host is terminated, the healthcheck will fail even if the host itself is fine.

The example you linked is basically a tutorial on how to setup such encapsulation system.

Sure, there is no requirement to do so if your use case case doesn't exactly fit this need and it'll work. Just that you'll likely endup creating another system to monitor the application on real servers (and update in Katran in time accordingly).

**Comment by kgs** [comment]
Ah, makes sense - check if real is actually able to serve given VIP was thing that I've missed! Without that I could only check if application on real serves content for its IP (packets without encapsulation) not exactly for VIP.

One bonus question is regarding this change https://github.com/facebookincubator/katran/pull/68 - as I understand example_grpc do not support this type of healtheck program (healthchecking_kern.o)? Main difference is it does not require IPIP interfaces to be up on host calling healthchecks? Is it recommended to use this new one or old one is just fine?

**Comment by udippant** [comment]
The change in https://github.com/facebookincubator/katran/pull/68 is independent of whether you use grpc or thrift. It is a library change to encapsulate the outgoing packets in the BPF program itself rather than redirecting packets to other interfaces like ipip.

>  Main difference is it does not require IPIP interfaces to be up on host calling healthchecks?

Yes.

> Is it recommended to use this new one or old one is just fine?

The old approach will work. The new approach however is cleaner in general since you do not need to create interfaces at host level and is also easier to debug.

**Comment by kgs** [comment]
> The change in #68 is independent of whether you use grpc or thrift. It is a library change to encapsulate the outgoing packets in the BPF program itself rather than redirecting packets to other interfaces like ipip.

Sure, I understand that this is library change. My question was rather if I am not mistaken regarding the fact that this feature is not integrated into example_grpc yet.
 
> > Is it recommended to use this new one or old one is just fine?
> 
> The old approach will work. The new approach however is cleaner in general since you do not need to create interfaces at host level and is also easier to debug.

Ok, I see, thanks!
