### ISSUE TITLE
Which offloads should be disabled on NIC when using Katran?

### ISSUE THREAD

**Issue by kgs** [facebookincubator/katran#133]
Hi,

I've noticed that Katran does not work well when GRO is on (retransmissions due to too big packets), what other offloads should be turned off for Katran to work optimally?

**Comment by udippant** [comment]
I added a step to turn off receive offloads in https://github.com/facebookincubator/katran/commit/9a8e863ffd028055e536f6632b91c0911c245491 

Closing.
