### ISSUE TITLE
Driver mode in lastes commit

### ISSUE THREAD

**Issue by bienkma** [facebookincubator/katran#136]
Hi there,

I saw that katran is the best performance in "driver mode". So I'm running katran but I can't find "driver mode" to run ./katran_server_grpc? How can I start katran by the mode instead of "generic" mode? Which option is?

**Comment by sharmafb** [comment]
You can do this by setting xdp_flags to be 1U << 2 (see https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/if_link.h#L1179 for the various modes of attachment of an XDP program). You need to make sure though, that your NIC driver supports XDP.
