### ISSUE TITLE
Misleading "File not found" error

### ISSUE THREAD

**Issue by kgs** [facebookincubator/katran#137]
Because of this change: https://github.com/facebookincubator/katran/pull/85, every time Katran is started (with healthcheck support) there is en error in logs in following format:

```
E1025 12:59:54.328714 20579 BpfAdapter.cpp:219] Error receiving netlink message: File exists [17]
```

I suggest at least either to make this as WARN or check first if clsact qdisk exists if possible.

Also, it is possible to make https://github.com/facebookincubator/katran/blob/main/EXAMPLE.md simpler by removing section with
```
$ sudo tc qd add  dev enp0s3 clsact
```

**Comment by avasylev** [comment]
@kgs please submit PR
