### ISSUE TITLE
lru_mappping type ARRAY_OF_MAPS

### ISSUE THREAD

**Issue by yugeshk** [facebookincubator/katran#138]
I was wondering why the [lru_mapping](https://github.com/facebookincubator/katran/blob/d4edcd2c5a9996c894f89b85c9234a992c642d21/katran/lib/bpf/balancer_maps.h#L43) BPF map uses the type `BPF_MAP_TYPE_ARRAY_OF_MAPS` and not `BPF_MAP_TYPE_LRU_PERCPU_HASH` when in fact the max size for the map is `MAX_SUPPORTED_CPUS` and is always indexed into by the processor id, thereby effectively making it a percpu map?

Is there some ingenious design choice here that I may be missing?

**Comment by udippant** [comment]
In BPF_MAP_TYPE_LRU_PERCPU_HASH, the values are copied across all the CPU specific maps, which wastes a lot of memory. So, Katran creates its own 'per-cpu' lru maps and indexes the fd (id) of each of these maps in another map-of-map with CPU as the key. This saves memory while also avoids necessity to take locks for cross cpu read / writes.

**Comment by yugeshk** [comment]
@udippant Thanks for the clarification! As a follow up (and this may be a bit more eBPF specific, but) my understanding of PERCPU_HASH and PERCPU_ARRAY maps was that each CPU has a separate copy of the map and that the copies are not kept synchronized across CPUs in any way. However, based on what you said, it seems like the same isn't the case for LRU_PERCPU_HASH, i.e., values in this maps are copied to all CPUs. Is this correct? 

Ref : [documentation from bcc](https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#7-bpf_percpu_hash)

**Comment by tehnerd** [comment]
https://www.linuxplumbersconf.org/event/2/contributions/109/attachments/107/134/LPC_XDP_Shirokov_v2.pdf page 48 + also per cpu flavor allocate for all_possible_cpus (when server supports hotplug) instead of just online_cpus. i've seen in some envs servers w/ 16 online cpus and 128 possible_cpus

**Comment by yugeshk** [comment]
@tehnerd Thanks this helped! Nice talk :)
