### ISSUE TITLE
How to spelling "Katran" in English

### ISSUE THREAD

**Issue by bienkma** [facebookincubator/katran#139]
Sorry, I don't understand how to spelling in English and where I can ask.

**Comment by kvtsoy** [comment]
Do you mean you want to know how to pronounce it? If so it's /katɹæn/ - like "cat" + "ran".

**Comment by bienkma** [comment]
Thank @kvtsoy . So why the name "Katran"?

**Comment by kvtsoy** [comment]
Described here: https://github.com/facebookincubator/katran#trivia
