### ISSUE TITLE
dperf: a high performance open source l4lb load tester

### ISSUE THREAD

**Issue by pengjianzhang** [facebookincubator/katran#150]
Dperf (https://github.com/baidu/dperf) is a DPDK based high performance L4L7 load tester. It can generate huge traffic with a single x86 server: tens of millions of HTTP CPS，hundreds of Gbps throughput and billions of connections.
I hope it's useful for you. thanks.

**Comment by udippant** [comment]
Thank you for sharing. Seems useful for stress tests. We'll keep an eye on it.

**Comment by pengjianzhang** [comment]
> Thank you for sharing. Seems useful for stress tests. We'll keep an eye on it.

yes. dperf is a L4LB load tester.  it's a DPDK ecosystem project now. We can see it here https://www.dpdk.org/ecosystem/ .
