### ISSUE TITLE
katran deploy and use document file

### ISSUE THREAD

**Issue by Farice4** [facebookincubator/katran#153]
@ahornby 
I'm trying to build Katran load balancing of Facebook, but I don't know how to use it. There is very little information on the Internet. Can you give me an install and use doc file?

I finish the build_katran.sh operation, but I can't finish the next operation.

**Comment by Farice4** [comment]
@sharma95
@sawravchy

**Comment by ahornby** [comment]
> @ahornby I'm trying to build Katran load balancing of Facebook, but I don't know how to use it. There is very little information on the Internet. Can you give me an install and use doc file?
> 
> I finish the build_katran.sh operation, but I can't finish the next operation.

@Farice4 I don't know how to use it I afraid (my commits have been for common Meta OSS build tooling).  EXAMPLE.md and USAGE.md might have some pointers

**Comment by Farice4** [comment]
@ahornby  Thanks, Katran documentation is too little, so I am not sure that I can continue.

**Comment by udippant** [comment]
@Farice4 here's an overview of the Katran project that explains the motivation and the use case - https://engineering.fb.com/2018/05/22/open-source/open-sourcing-katran-a-scalable-network-load-balancer/ . 

> but I don't know how to use it 

Can you briefly explain what is your use case, and what problems you are running into? At its core, Katran is a L4 service that helps in the better management and  scaling of the L7 services. Are you having issues to set up of Katran properly ? Or are you trying to understand its use cases?
