### ISSUE TITLE
what is the bleesed way to build opensource version

### ISSUE THREAD

**Issue by tehnerd** [facebookincubator/katran#158]
subj. in the past it was just ./build_katran.sh inside ubuntu 18.04 env, but nowadays it fails to do so. So looks like documentation (EXAMPLE.md) is outdated. Could you folks provide "blessed" way and env to build it?

**Comment by dwdrajesh** [comment]
Hi were you able to find the answer to 'how to build/run on an ubuntu VM'? Thanks

**Comment by tehnerd** [comment]
nope, no reply from FB folks.

**Comment by tehnerd** [comment]
Personally I'm ok with any env. As long as it tested. Eg if internally you folks builds on RH/Centos - that would works. As long as there is a documented way how anyone could take clean centos container, run something, and as result would have a complete build

**Comment by tehnerd** [comment]
so what is the conclusion here? are you folks going to give us a way to build open sourced version in "blessed way / env"? e.g. i can see that https://github.com/facebookincubator/katran/commit/4871cde798481afecca99aedf7e30d3157c3233b broke open sourced example server, since constructor for KatranLb changed it's signature, but nothing in example section was modified

**Comment by avasylev** [comment]
@lima1756 updated setup to Ubuntu 20 - OSS build is passing fine now and we also have github action continuously building on Ubuntu 20. It's past our internal flow for diff landing, but should lets us catch issues fast.

While github action builds on Ubuntu, it doesn't use build_katran.sh but getdeps. Midterm we plan to replace build_katran.sh with getdeps similar to what Folly does https://github.com/facebook/folly#getdepspy.
