### ISSUE TITLE
small probability outer ip header checksum error

### ISSUE THREAD

**Issue by duanxiongchun** [facebookincubator/katran#16]
we test katran in our environment。and find some  outer ip header checksum error about （1/100000）rate 。
I check the code in katran/lib/bpf/pckt_encap.h。
in some Small probability 。(csum & 0xffff) + (csum >> 16) may be  overflow in 16bit。 it‘s may cause the problem I had mention

after fix code  under groud。 this problem disappear。

\-  iph->check = ~((csum & 0xffff) + (csum >> 16));
\+  csum = (csum & 0xffff) + (csum >> 16);
\+  csum += (csum >>16);
\+  iph->check = ~(csum);

thanks。

**Comment by tehnerd** [comment]
Thanks. Will look and fix

**Comment by duanxiongchun** [comment]
using 64bit csum， it look like no change to overflow 。 great！

**Comment by tehnerd** [comment]
@duanxiongchun  could you please share your setup (src addr + port + what real address you are using) so i can reproduce this error internally. just to make sure that our fix is, well, fixing it.

**Comment by tehnerd** [comment]
nvm. found few examples

**Comment by tehnerd** [comment]
should be fixed with latest commit. thanks for reporting

**Comment by duanxiongchun** [comment]
write a test to request 1000000 time, you will find one in most  probability
