### ISSUE TITLE
License question 

### ISSUE THREAD

**Issue by srinikom** [facebookincubator/katran#160]
Would you guys consider a dual license or permissive license? Something similar to BPF_MAP_TYPE_RINGBUF would work great for our use case.

SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

This would let end users to use maps which are relevant for their license/use cases.

Thanks again for a great software. Some discussion before with my latest comments here: https://github.com/facebookincubator/katran/issues/25

**Comment by jdryan** [comment]
@srinikom -- I'm looking into this, will get back to you
