### ISSUE TITLE
Can I use Katran with autoscaling enabled for backend servers?

### ISSUE THREAD

**Issue by RuchiSaluja8** [facebookincubator/katran#168]
Hi,

I am new here and I have read the initial documents (README, USAGE, DEVELOPING). As mentioned in the USAGE doc, there is a mechanism to add new 'Reals' to a VIP along with its weight. How can this step be done when the Katran load balancer is already running? Specifically, I am talking about the case when autoscaling is enabled for backend servers and I want the load balancer to consider the newly added server also.

Any help would be much appreciated! TIA.

**Comment by frankfeir** [comment]
Hi,

As mentioned in USAGE.md, katran consists of two parts as below. they run at the same time.

1. BPF code for actual forwarding (which is used in XDP attachment
  point; code located at lib/bpf/ folder).

2. C++ library to interact w/ BPF forwarding plane.

when the bpf program is loaded and attached, it starts to forward packets based on the packet info and bpf maps updated by c++ library.
While bpf program is running, you can call "lb.addRealForVip(real, vip);" to add new real server to a existiing VIP with the weight info. katranLb will update related bpf maps accordingly to be used in the BPF forwarding plane. 

EXAMPLE.md provides examples on how katran library can be used.
