### ISSUE TITLE
Decapsulation of IPIP packets

### ISSUE THREAD

**Issue by jprukner** [facebookincubator/katran#17]
Hello! I get the way non-IPIP packets are processed on L4 nodes. But what does happen to them once they get to L7 node? Is there also Katran that does the decapsulation? I've been reading the BPF code and there are some signs Katran does this when `INLINE_DECAP` is set. And then there is a function `process_encaped_pckt` that actually does the decapsulation I think.

I assume that Kartan is also supposed to run on L7 nodes and do the decapsulation of IPIP packets. Could you please tell whether my assumption is correct or not?

**Comment by tehnerd** [comment]
see EXAMPLE.md (https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md)  on how to configure "real" (L7 load balancer). see "Configuration of forwarding plane" section in that doc: it describes how to configure ipip decapsulation interface on L7 side w/ usual linux tools (ip link add etc)

**Comment by tehnerd** [comment]
let me know if you have any other question after reading this doc

**Comment by jprukner** [comment]
Thanks, I am closing the issue.
