### ISSUE TITLE
Benchmarks to test katran.

### ISSUE THREAD

**Issue by liusy58** [facebookincubator/katran#170]
I wonder if there exist some benchmarks to test katran?

**Comment by avasylev** [comment]
We run internally in Meta infra, but these would be very hard to open source, heavily dependent on internal infra.

Having open source benchmark for katran would awesome, we'd be happy to take PR if anyone is interested.

**Comment by jdryan** [comment]
Hey @liusy58  -- as @avasylev mentions we don't have formal benchmarking like you are probably asking about. You can get some measurements from the --perf-testing option to katran_tester, though.
