### ISSUE TITLE
build simple_katran_client failed

### ISSUE THREAD

**Issue by yangxingwu** [facebookincubator/katran#19]
[ 95%] Building CXX object example/CMakeFiles/simple_katran_client.dir/client/Main.cpp.o
collect2: error: ld returned 1 exit status
example_grpc/CMakeFiles/katran_server_grpc.dir/build.make:134: recipe for target 'example_grpc/katran_server_grpc' failed
make[2]: *** [example_grpc/katran_server_grpc] Error 1
CMakeFiles/Makefile2:1242: recipe for target 'example_grpc/CMakeFiles/katran_server_grpc.dir/all' failed
make[1]: *** [example_grpc/CMakeFiles/katran_server_grpc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Linking CXX executable simple_katran_client
collect2: error: ld returned 1 exit status
example/CMakeFiles/simple_katran_client.dir/build.make:147: recipe for target 'example/simple_katran_client' failed
make[2]: *** [example/simple_katran_client] Error 1
CMakeFiles/Makefile2:858: recipe for target 'example/CMakeFiles/simple_katran_client.dir/all' failed
make[1]: *** [example/CMakeFiles/simple_katran_client.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tehnerd** [comment]
what os/ revesion of the code you are using? recent build by travis was successful  (https://travis-ci.org/facebookincubator/katran) so looks like this is specific for your environment.
you could try
1) update code to the latest revision
2) inside katran folder delete "deps" directory (this one is created during the run of build_katran.sh script and this is where we download all of our external dependencies; mb you are using some outdated version of folly or any other library)
3) rerun build_katran.sh script

if issue still persist - please paste last ~100-500 lines of the output from the build. current output shows that there was an issue but actual lines with issues was, unfortunately, omitted.

**Comment by tehnerd** [comment]
please reopen the issue if you still can't build it. for now our CI system shows no issue with a build on ubuntu 18.04
