### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by victorstewart** [facebookincubator/katran#211]
building on Clear Linux (6.6) with GCC 13.2.1 with this command `python3 ./build/fbcode_builder/getdeps.py --allow-system-packages build katran` and got this error:

> /tmp/fbcode_builder_getdeps-ZrootZkatranZbuildZfbcode_builder-root/repos/github.com-facebookincubator-katran.git/katran/lib/BpfLoader.cpp: In function ‘std::string katran::{anonymous}::libBpfErrMsg(int)’:
> /tmp/fbcode_builder_getdeps-ZrootZkatranZbuildZfbcode_builder-root/repos/github.com-facebookincubator-katran.git/katran/lib/BpfLoader.cpp:46:25: error: variable ‘std::array<char, 128> buf’ has initializer but incomplete type
>    46 |   std::array<char, 128> buf{};
>       |                         ^~~
> [17/80] Building CXX object katran/lib/CMakeFiles/katranlb.dir/KatranLb.cpp.o

so i just manually edited BpfLoader.cpp to add `#include <array>` at the top, then it built successfully.

**Comment by 7anya** [comment]
The above solution did not work for me, i get 

std::array<char, 128> buf’ has initializer but incomplete type
   46 |   std::array<char, 128> buf{};
      |                         ^~~
[25/80] Building CXX object katran/lib/CMakeFiles/katranlb.dir/KatranLb.cpp.o
ninja: build stopped: subcommand failed.
