### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by moeinshahcheraghi** [facebookincubator/katran#212]
building on Ubuntu 20.04 with this command ./build_katran.sh i get the following error

![Screenshot from 2024-01-06 16-31-05](https://github.com/facebookincubator/katran/assets/115411048/f1d19f45-a70a-4917-aad3-8fd254dc9ca4)

**Comment by lima1756** [comment]
can you share the error as a txt file?

**Comment by moeinshahcheraghi** [comment]
/root/katran/_build/deps/include/fmt/core.h:1595:17: note: ‘formattable_char’ evaluates to false
make[2]: *** [CMakeFiles/folly_base.dir/build.make:272: CMakeFiles/folly_base.dir/folly/IPAddress.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/folly_base.dir/build.make:286: CMakeFiles/folly_base.dir/folly/IPAddressV4.cpp.o] Error 1
In file included from /root/katran/_build/deps/include/fmt/format.h:55,
                 from /root/katran/_build/deps/folly/folly/FBString.h:34,
                 from /root/katran/_build/deps/folly/folly/IPAddressV6.h:37,
                 from /root/katran/_build/deps/folly/folly/IPAddressV6.cpp:17:
/root/katran/_build/deps/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/root/katran/_build/deps/include/fmt/core.h:1848:51:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {folly::Range<const char*>}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {folly::Range<const char*>}]’
/root/katran/_build/deps/include/fmt/core.h:1866:18:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_const<T>::type ...> fmt::v10::make_format_args(T& ...) [with Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = {folly::Range<const char*>}]’
/root/katran/_build/deps/include/fmt/core.h:2845:44:   required from ‘fmt::v10::basic_string<Char> fmt::v10::format(fmt::v10::format_string<T ...>, T&& ...) [with T = {folly::Range<const char*>&}; Char = char; fmt::v10::basic_string<Char> = std::__cxx11::basic_string<char>; fmt::v10::format_string<T ...> = fmt::v10::basic_format_string<char, folly::Range<const char*>&>]’
/root/katran/_build/deps/folly/folly/IPAddressV6.cpp:216:20:   required from here
/root/katran/_build/deps/include/fmt/core.h:1595:17: error: static assertion failed: Mixing character types is disallowed.
 1595 |   static_assert(formattable_char, "Mixing character types is disallowed.");
      |                 ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/include/fmt/core.h:1595:17: note: ‘formattable_char’ evaluates to false
make[2]: *** [CMakeFiles/folly_base.dir/build.make:300: CMakeFiles/folly_base.dir/folly/IPAddressV6.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/folly_base.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by 2shsh** [comment]
same issue for me

**Comment by lima1756** [comment]
should have been fixed with https://github.com/facebookincubator/katran/pull/222
