### ISSUE TITLE
Error executing ./build_katran.sh

### ISSUE THREAD

**Issue by pratikdk** [facebookincubator/katran#219]
**gcc version 13.1.0 (Ubuntu 13.1.0-8ubuntu1~22.04) 
Ubuntu clang version 17.0.6 
cmake version `3.22.1**

cmd:
sudo ./build_katran.sh

Below is the error:
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/IPAddressV6.cpp.o
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/MacAddress.cpp.o
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/MicroLock.cpp.o
In file included from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddress.cpp:28:
/home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/small_vector.h: In instantiation of ‘folly::small_vector<T, M, P>::small_vector(folly::small_vector<T, M, P>&&) [with Value = folly::Range<const char*>; long unsigned int RequestedMaxInline = 2; Policy = void]’:
/home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddress.cpp:78:10:   required from here
/home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/small_vector.h:557:20: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘folly::small_vector<folly::Range<const char*>, 2, void>::value_type’ {aka ‘class folly::Range<const char*>’} with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  557 |         std::memcpy(u.buffer(), o.u.buffer(), MaxInline * kSizeOfValue);
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddressV4.h:36,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddress.h:38,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddress.cpp:17:
/home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/Range.h:248:7: note: ‘folly::small_vector<folly::Range<const char*>, 2, void>::value_type’ {aka ‘class folly::Range<const char*>’} declared here
  248 | class Range {
      |       ^~~~~
In file included from /home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/format.h:54,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/FBString.h:34,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddressV4.h:34:
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::context; T = folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1991:74:   required from ‘constexpr fmt::v10::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v10::make_format_args(T& ...) [with Context = context; T = {folly::Range<const char*>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/format.h:4367:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {folly::Range<const char*>&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, folly::Range<const char*>&>]’
/home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddress.cpp:100:47:   required from here
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1583:17: error: static assertion failed: Mixing character types is disallowed.
 1583 |   static_assert(formattable_char, "Mixing character types is disallowed.");
      |                 ^~~~~~~~~~~~~~~~
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1583:17: note: ‘formattable_char’ evaluates to false
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::context; T = const folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1991:74:   required from ‘constexpr fmt::v10::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v10::make_format_args(T& ...) [with Context = context; T = {const folly::Range<const char*>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/format.h:4367:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {const folly::Range<const char*>&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, const folly::Range<const char*>&>]’
/home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddress.cpp:113:22:   required from here
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1583:17: error: static assertion failed: Mixing character types is disallowed.
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1583:17: note: ‘formattable_char’ evaluates to false
In file included from /home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/format.h:54,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/FBString.h:34,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddressV4.h:34,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddressV4.cpp:17:
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::context; T = folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1991:74:   required from ‘constexpr fmt::v10::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v10::make_format_args(T& ...) [with Context = context; T = {folly::Range<const char*>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/format.h:4367:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {folly::Range<const char*>&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, folly::Range<const char*>&>]’
/home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddressV4.cpp:73:20:   required from here
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1583:17: error: static assertion failed: Mixing character types is disallowed.
 1583 |   static_assert(formattable_char, "Mixing character types is disallowed.");
      |                 ^~~~~~~~~~~~~~~~
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1583:17: note: ‘formattable_char’ evaluates to false
make[2]: *** [CMakeFiles/folly_base.dir/build.make:272: CMakeFiles/folly_base.dir/folly/IPAddress.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/folly_base.dir/build.make:286: CMakeFiles/folly_base.dir/folly/IPAddressV4.cpp.o] Error 1
In file included from /home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/format.h:54,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/FBString.h:34,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddressV6.h:37,
                 from /home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddressV6.cpp:17:
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::context; T = folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1991:74:   required from ‘constexpr fmt::v10::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v10::make_format_args(T& ...) [with Context = context; T = {folly::Range<const char*>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/format.h:4367:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {folly::Range<const char*>&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, folly::Range<const char*>&>]’
/home/pratik/Downloads/katran_dump/katran/_build/deps/folly/folly/IPAddressV6.cpp:216:20:   required from here
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1583:17: error: static assertion failed: Mixing character types is disallowed.
 1583 |   static_assert(formattable_char, "Mixing character types is disallowed.");
      |                 ^~~~~~~~~~~~~~~~
/home/pratik/Downloads/katran_dump/katran/_build/deps/include/fmt/base.h:1583:17: note: ‘formattable_char’ evaluates to false
make[2]: *** [CMakeFiles/folly_base.dir/build.make:300: CMakeFiles/folly_base.dir/folly/IPAddressV6.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/folly_base.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by lalitg845** [comment]
katran is currently supported on gcc version 11.4.0 and clang version 14.0.0

**Comment by Allojpass** [comment]
The problem has not been resolved with version updates

**Comment by lima1756** [comment]
fixed in https://github.com/facebookincubator/katran/pull/222
if still not working please open a new issue with the new log
