### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Allojpass** [facebookincubator/katran#220]
Scanning dependencies of target folly_base
[  0%] Building CXX object CMakeFiles/folly_base.dir/folly/CancellationToken.cpp.o
[  0%] Building CXX object CMakeFiles/folly_base.dir/folly/ClockGettimeWrappers.cpp.o
[  1%] Building CXX object CMakeFiles/folly_base.dir/folly/Conv.cpp.o
[  1%] Building CXX object CMakeFiles/folly_base.dir/folly/Demangle.cpp.o
[  1%] Building CXX object CMakeFiles/folly_base.dir/folly/Executor.cpp.o
[  2%] Building CXX object CMakeFiles/folly_base.dir/folly/ExceptionWrapper.cpp.o
[  2%] Building CXX object CMakeFiles/folly_base.dir/folly/File.cpp.o
[  2%] Building CXX object CMakeFiles/folly_base.dir/folly/ExceptionString.cpp.o
[  2%] Building CXX object CMakeFiles/folly_base.dir/folly/FileUtil.cpp.o
[  3%] Building CXX object CMakeFiles/folly_base.dir/folly/Fingerprint.cpp.o
[  3%] Building CXX object CMakeFiles/folly_base.dir/folly/FollyMemcpy.cpp.o
[  3%] Building CXX object CMakeFiles/folly_base.dir/folly/FollyMemset.cpp.o
[  4%] Building CXX object CMakeFiles/folly_base.dir/folly/Format.cpp.o
[  4%] Building CXX object CMakeFiles/folly_base.dir/folly/GroupVarint.cpp.o
[  4%] Building CXX object CMakeFiles/folly_base.dir/folly/IPAddress.cpp.o
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/IPAddressV4.cpp.o
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/IPAddressV6.cpp.o
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/MacAddress.cpp.o
[  5%] Building CXX object CMakeFiles/folly_base.dir/folly/MicroLock.cpp.o
[  6%] Building CXX object CMakeFiles/folly_base.dir/folly/Random.cpp.o
In file included from /root/katran-main/_build/deps/include/fmt/format.h:54,
                 from /root/katran-main/_build/deps/folly/folly/FBString.h:35,
                 from /root/katran-main/_build/deps/folly/folly/IPAddressV4.h:34,
                 from /root/katran-main/_build/deps/folly/folly/IPAddressV4.cpp:17:
/root/katran-main/_build/deps/include/fmt/base.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::context; T = folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/root/katran-main/_build/deps/include/fmt/base.h:2005:74:   required from ‘constexpr fmt::v10::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v10::make_format_args(T& ...) [with Context = fmt::v10::context; T = {folly::Range<const char*>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/root/katran-main/_build/deps/include/fmt/format.h:4370:44:   required from ‘std::string fmt::v10::format(fmt::v10::format_string<T ...>, T&& ...) [with T = {folly::Range<const char*>&}; std::string = std::__cxx11::basic_string<char>; fmt::v10::format_string<T ...> = fmt::v10::basic_format_string<char, folly::Range<const char*>&>]’
/root/katran-main/_build/deps/folly/folly/IPAddressV4.cpp:73:20:   required from here
/root/katran-main/_build/deps/include/fmt/base.h:1597:17: error: static assertion failed: Mixing character types is disallowed.
 1597 |   static_assert(formattable_char, "Mixing character types is disallowed.");
      |                 ^~~~~~~~~~~~~~~~
/root/katran-main/_build/deps/include/fmt/base.h:1597:17: note: ‘formattable_char’ evaluates to false
In file included from /root/katran-main/_build/deps/include/fmt/format.h:54,
                 from /root/katran-main/_build/deps/folly/folly/FBString.h:35,
                 from /root/katran-main/_build/deps/folly/folly/IPAddressV4.h:34,
                 from /root/katran-main/_build/deps/folly/folly/IPAddress.h:38,
                 from /root/katran-main/_build/deps/folly/folly/IPAddress.cpp:17:
/root/katran-main/_build/deps/include/fmt/base.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::context; T = folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/root/katran-main/_build/deps/include/fmt/base.h:2005:74:   required from ‘constexpr fmt::v10::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v10::make_format_args(T& ...) [with Context = fmt::v10::context; T = {folly::Range<const char*>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/root/katran-main/_build/deps/include/fmt/format.h:4370:44:   required from ‘std::string fmt::v10::format(fmt::v10::format_string<T ...>, T&& ...) [with T = {folly::Range<const char*>&}; std::string = std::__cxx11::basic_string<char>; fmt::v10::format_string<T ...> = fmt::v10::basic_format_string<char, folly::Range<const char*>&>]’
/root/katran-main/_build/deps/folly/folly/IPAddress.cpp:100:47:   required from here
/root/katran-main/_build/deps/include/fmt/base.h:1597:17: error: static assertion failed: Mixing character types is disallowed.
 1597 |   static_assert(formattable_char, "Mixing character types is disallowed.");
      |                 ^~~~~~~~~~~~~~~~
/root/katran-main/_build/deps/include/fmt/base.h:1597:17: note: ‘formattable_char’ evaluates to false
/root/katran-main/_build/deps/include/fmt/base.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::context; T = const folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/root/katran-main/_build/deps/include/fmt/base.h:2005:74:   required from ‘constexpr fmt::v10::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v10::make_format_args(T& ...) [with Context = fmt::v10::context; T = {const folly::Range<const char*>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/root/katran-main/_build/deps/include/fmt/format.h:4370:44:   required from ‘std::string fmt::v10::format(fmt::v10::format_string<T ...>, T&& ...) [with T = {const folly::Range<const char*>&}; std::string = std::__cxx11::basic_string<char>; fmt::v10::format_string<T ...> = fmt::v10::basic_format_string<char, const folly::Range<const char*>&>]’
/root/katran-main/_build/deps/folly/folly/IPAddress.cpp:113:22:   required from here
/root/katran-main/_build/deps/include/fmt/base.h:1597:17: error: static assertion failed: Mixing character types is disallowed.
/root/katran-main/_build/deps/include/fmt/base.h:1597:17: note: ‘formattable_char’ evaluates to false
In file included from /root/katran-main/_build/deps/include/fmt/format.h:54,
                 from /root/katran-main/_build/deps/folly/folly/FBString.h:35,
                 from /root/katran-main/_build/deps/folly/folly/IPAddressV6.h:37,
                 from /root/katran-main/_build/deps/folly/folly/IPAddressV6.cpp:17:
/root/katran-main/_build/deps/include/fmt/base.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::context; T = folly::Range<const char*>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
/root/katran-main/_build/deps/include/fmt/base.h:2005:74:   required from ‘constexpr fmt::v10::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v10::make_format_args(T& ...) [with Context = fmt::v10::context; T = {folly::Range<const char*>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
/root/katran-main/_build/deps/include/fmt/format.h:4370:44:   required from ‘std::string fmt::v10::format(fmt::v10::format_string<T ...>, T&& ...) [with T = {folly::Range<const char*>&}; std::string = std::__cxx11::basic_string<char>; fmt::v10::format_string<T ...> = fmt::v10::basic_format_string<char, folly::Range<const char*>&>]’
/root/katran-main/_build/deps/folly/folly/IPAddressV6.cpp:216:20:   required from here
/root/katran-main/_build/deps/include/fmt/base.h:1597:17: error: static assertion failed: Mixing character types is disallowed.
 1597 |   static_assert(formattable_char, "Mixing character types is disallowed.");
      |                 ^~~~~~~~~~~~~~~~
/root/katran-main/_build/deps/include/fmt/base.h:1597:17: note: ‘formattable_char’ evaluates to false
make[2]: *** [CMakeFiles/folly_base.dir/build.make:286: CMakeFiles/folly_base.dir/folly/IPAddressV4.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/folly_base.dir/build.make:272: CMakeFiles/folly_base.dir/folly/IPAddress.cpp.o] Error 1
make[2]: *** [CMakeFiles/folly_base.dir/build.make:300: CMakeFiles/folly_base.dir/folly/IPAddressV6.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/folly_base.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
root@ggboy-virtual-machine:~/katran-main# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
root@ggboy-virtual-machine:~/katran-main# clang -v
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by PooyaEimandar** [comment]
Same issue on both Ubuntu 22.04 & 20.04  - arm64

**Comment by hedianxin** [comment]
Anyone solved the issue? How can run the folly without fmt?

**Comment by lima1756** [comment]
fixed in https://github.com/facebookincubator/katran/pull/222
if still not working please open a new issue with the new log
