### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hedianxin** [facebookincubator/katran#221]
my gcc version 12.3.0In file included from /usr/local/include/folly/CppAttributes.h:25,
                 from /usr/local/include/folly/Function.h:215,
                 from /usr/local/include/folly/Executor.h:23,
                 from /usr/local/include/folly/io/async/EventBase.h:37,
                 from /usr/local/include/folly/io/async/AsyncSignalHandler.h:21,
                 from /home/shenjie/katran/example_grpc/GrpcSignalHandler.h:21,
                 from /home/shenjie/katran/example_grpc/GrpcSignalHandler.cpp:17:
/usr/local/include/folly/Portability.h:35:31: error: static assertion failed: __cplusplus >= 201703L
   35 | static_assert(FOLLY_CPLUSPLUS >= 201703L, "__cplusplus >= 201703L");
      |                               ^
/usr/local/include/folly/Portability.h:35:31: note: the comparison reduces to ‘(201402 >= 201703)’
In file included from /usr/local/include/folly/Function.h:217:
/usr/local/include/folly/Traits.h:1141:10: error: ‘is_default_constructible_v’ is not a member of ‘std’; did you mean ‘is_default_constructible’?
 1141 |     std::is_default_constructible_v<Hasher> &&
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |          is_default_constructible
/usr/local/include/folly/Traits.h:1141:10: error: ‘is_default_constructible_v’ is not a member of ‘std’; did you mean ‘is_default_constructible’?
 1141 |     std::is_default_constructible_v<Hasher> &&
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |          is_default_constructible
/usr/local/include/folly/Traits.h:1141:43: error: template argument 2 is invalid
 1141 |     std::is_default_constructible_v<Hasher> &&
      |                                           ^
/usr/local/include/folly/Traits.h:1153:5: error: ‘is_hasher_usable’ was not declared in this scope; did you mean ‘is_hasher_usable_v’?
 1153 |     is_hasher_usable<T, Hasher>::value;
      |     ^~~~~~~~~~~~~~~~
      |     is_hasher_usable_v
/usr/local/include/folly/Traits.h:1153:23: error: expected primary-expression before ‘,’ token
 1153 |     is_hasher_usable<T, Hasher>::value;
      |                       ^
/usr/local/include/folly/Function.h:419:8: error: redefinition of ‘struct folly::detail::function::FunctionTraits<ReturnType(Args ...)>’
  419 | struct FunctionTraits<ReturnType(Args...) noexcept> {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/folly/Function.h:333:8: note: previous definition of ‘struct folly::detail::function::FunctionTraits<ReturnType(Args ...)>’
  333 | struct FunctionTraits<ReturnType(Args...)> {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/folly/Function.h:465:8: error: redefinition of ‘struct folly::detail::function::FunctionTraits<ReturnType(Args ...) const>’
  465 | struct FunctionTraits<ReturnType(Args...) const noexcept> {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/folly/Function.h:376:8: note: previous definition of ‘struct folly::detail::function::FunctionTra

**Comment by lima1756** [comment]
fixed in https://github.com/facebookincubator/katran/pull/222
if still not working please open a new issue with the new log
