### ISSUE TITLE
build_kataran.sh folly build error(I have used the #222

### ISSUE THREAD

**Issue by hedianxin** [facebookincubator/katran#224]
: In function ‘void folly::detail::singletonWarnDoubleRegistrationAndAbort(const folly::detail::TypeDescriptor&)’:
/root/katran/_build/deps/folly/folly/Singleton.cpp:86:16: error: ‘runtime’ is not a member of ‘fmt’
   86 |           fmt::runtime( //
      |                ^~~~~~~
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:40:23: note: in definition of macro ‘FOLLY_DETAIL_SAFE_CHECK_IMPL’
   40 |                       __VA_ARGS__))>::value.data};                        \
      |                       ^~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:84:3: note: in expansion of macro ‘FOLLY_SAFE_FATAL’
   84 |   FOLLY_SAFE_FATAL( // May happen before registrationComplete().
      |   ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:86:16: error: ‘runtime’ is not a member of ‘fmt’
   86 |           fmt::runtime( //
      |                ^~~~~~~
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:40:23: note: in definition of macro ‘FOLLY_DETAIL_SAFE_CHECK_IMPL’
   40 |                       __VA_ARGS__))>::value.data};                        \
      |                       ^~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:84:3: note: in expansion of macro ‘FOLLY_SAFE_FATAL’
   84 |   FOLLY_SAFE_FATAL( // May happen before registrationComplete().
      |   ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:40:36: error: template argument 1 is invalid
   40 |                       __VA_ARGS__))>::value.data};                        \
      |                                    ^
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:102:3: note: in expansion of macro ‘FOLLY_DETAIL_SAFE_CHECK_IMPL’
  102 |   FOLLY_DETAIL_SAFE_CHECK_IMPL(0, 0, 1, false, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:84:3: note: in expansion of macro ‘FOLLY_SAFE_FATAL’
   84 |   FOLLY_SAFE_FATAL( // May happen before registrationComplete().
      |   ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:86:16: error: ‘runtime’ is not a member of ‘fmt’
   86 |           fmt::runtime( //
      |                ^~~~~~~
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:44:46: note: in definition of macro ‘FOLLY_DETAIL_SAFE_CHECK_IMPL’
   44 |       __folly_detail_safe_assert_terminate_w(__VA_ARGS__);                \
      |                                              ^~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:84:3: note: in expansion of macro ‘FOLLY_SAFE_FATAL’
   84 |   FOLLY_SAFE_FATAL( // May happen before registrationComplete().
      |   ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp: In function ‘void folly::detail::singletonWarnLeakyDoubleRegistrationAndAbort(const folly::detail::TypeDescriptor&)’:
/root/katran/_build/deps/folly/folly/Singleton.cpp:98:16: error: ‘runtime’ is not a member of ‘fmt’
   98 |           fmt::runtime( //
      |                ^~~~~~~
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:40:23: note: in definition of macro ‘FOLLY_DETAIL_SAFE_CHECK_IMPL’
   40 |                       __VA_ARGS__))>::value.data};                        \
      |                       ^~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:96:3: note: in expansion of macro ‘FOLLY_SAFE_FATAL’
   96 |   FOLLY_SAFE_FATAL( // May happen before registrationComplete().
      |   ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:98:16: error: ‘runtime’ is not a member of ‘fmt’
   98 |           fmt::runtime( //

**Comment by lima1756** [comment]
using https://github.com/facebookincubator/katran/issues/225 as main thread, closing this
