### ISSUE TITLE
I hava some problems with the relationship between folly and fmt，I use git to install fmt then folly build by build_katran.sh go wrong like #221 while without fmt meet the problem like under

### ISSUE THREAD

**Issue by hedianxin** [facebookincubator/katran#225]

**Comment by hedianxin** [comment]
/katran/_build/deps/folly/folly/Singleton.cpp:86:16: error: ‘runtime’ is not a member of ‘fmt’
   86 |           fmt::runtime( //
      |                ^~~~~~~
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:40:23: note: in definition of macro ‘FOLLY_DETAIL_SAFE_CHECK_IMPL’
   40 |                       __VA_ARGS__))>::value.data};                        \
      |                       ^~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:84:3: note: in expansion of macro ‘FOLLY_SAFE_FATAL’
   84 |   FOLLY_SAFE_FATAL( // May happen before registrationComplete().
      |   ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:86:16: error: ‘runtime’ is not a member of ‘fmt’
   86 |           fmt::runtime( //
      |                ^~~~~~~
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:40:23: note: in definition of macro ‘FOLLY_DETAIL_SAFE_CHECK_IMPL’
   40 |                       __VA_ARGS__))>::value.data};                        \
      |                       ^~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:84:3: note: in expansion of macro ‘FOLLY_SAFE_FATAL’
   84 |   FOLLY_SAFE_FATAL( // May happen before registrationComplete().
      |   ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:40:36: error: template argument 1 is invalid
   40 |                       __VA_ARGS__))>::value.data};                        \
      |                                    ^
/root/katran/_build/deps/folly/folly/lang/SafeAssert.h:102:3: note: in expansion of macro ‘FOLLY_DETAIL_SAFE_CHECK_IMPL’
  102 |   FOLLY_DETAIL_SAFE_CHECK_IMPL(0, 0, 1, false, __VA_ARGS__)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:84:3: note: in expansion of macro ‘FOLLY_SAFE_FATAL’
   84 |   FOLLY_SAFE_FATAL( // May happen before registrationComplete().
      |   ^~~~~~~~~~~~~~~~
/root/katran/_build/deps/folly/folly/Singleton.cpp:86:16: error: ‘runtime’ is not a member of ‘fmt’
   86 |           fmt::runtime( //
      |                ^~~~~~~

**Comment by lima1756** [comment]
https://github.com/facebookincubator/katran/issues/223
https://github.com/facebookincubator/katran/issues/224

Keeping this as the main issue, please keep the conversation in a single thread so it's easier to follow and it doesn't spam us. 
Looking into this

**Comment by lima1756** [comment]
@hedianxin  can you please share a copy of the full log?

You can do this by running
`./build_katran.sh &>> log.txt`
Once you have this upload it as a [gist](https://gist.github.com/) and share it here

**Comment by hedianxin** [comment]
[log.txt](https://github.com/facebookincubator/katran/files/14712759/log.txt)

**Comment by lima1756** [comment]
I see that your libfmt-dev version is 6, can you try upgrading it to version 8
```
Package: libfmt-dev
Architecture: amd64
Version: 8.1.1+ds1-2
```
If not possible through apt, you can download the package directly from here: https://packages.ubuntu.com/source/jammy/fmtlib

**Comment by hedianxin** [comment]
thx,it works
