### ISSUE TITLE
Some questions about balancer map ```global_lru_maps``` 

### ISSUE THREAD

**Issue by tacslon** [facebookincubator/katran#227]
Hi everyone, I have some questions about BPF map  ```global_lru_maps```, which really made me confused:
1. What does **global** here mean? Does it mean this map can be retrieved by Katrans in different LBs?
2. Where is ```global_lru_maps``` updated? I can find where ```lru_mappings``` is updated, but I can not find where ```global_lru_maps``` is updated.

**Comment by avasylev** [comment]
Regular lru maps are updated by katran code based on incoming packets. `global_lru_maps` provides additional layer that can be synchronized across multiple katran instances. Synchronization code is not open sourced (yet).
