### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by actaeon** [facebookincubator/katran#25]
Are you folks set on using GNU 2.0 as a license? Are you willing to consider using MIT or Apache?

**Comment by tehnerd** [comment]
We are using bpf_get_ktime_ns helper in balancer code. This bpf helper is marked as GPL only from kernel POV (is bpf program has anything else in license section - it won’t load). So we are kinda forced to use GPL

**Comment by actaeon** [comment]
Thanks for the response.

**Comment by srinikom** [comment]
I searched the repo for bpf_get_ktime_ns now and it is not referenced anymore. Can you guys please reconsider this? Something similar to BPF_MAP_TYPE_RINGBUF would work great for our use case. 

SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

This would let end users to use the maps which are relevant for their license use cases. 

Thanks for a great software.

**Comment by tehnerd** [comment]
https://github.com/facebookincubator/katran/blob/main/katran/lib/bpf/balancer_kern.c#L45

**Comment by srinikom** [comment]
Thanks. Yea - looks like I was searching for bpf_get_ktime_ns instead of bpf_ktime_get_ns. I see there are only two instances. Let me see if there is any alternative for this. 

Is this the only dependency?

**Comment by srinikom** [comment]
Looks like it is modified in Mar/2020.

-	.gpl_only	= true,
+	.gpl_only	= false,

PR/Patch - here: https://lists.openwall.net/netdev/2020/04/20/292 

Latest version here: https://elixir.bootlin.com/linux/latest/source/kernel/bpf/helpers.c#L155

**Comment by tehnerd** [comment]
i do not work at facebook anymore. so no idea what are their plan related to licensing. probably it is better to create a new issue, so current employees would see your proposal (i was notified because replied for original question, not sure that fb folks was notified as well)

**Comment by srinikom** [comment]
Thanks - opened a new issue https://github.com/facebookincubator/katran/issues/160
