### ISSUE TITLE
Compilation error from build_katran.sh

### ISSUE THREAD

**Issue by kahou82** [facebookincubator/katran#27]
I ran ./build_katran.sh and got this error:

```
/home/kahou/katran/deps/grpc/third_party/boringssl/crypto/x509/x509_test.cc: In member function ‘virtual void X509Test_ZeroLengthsWithX509PARAM_Test::TestBody()’:
/home/kahou/katran/deps/grpc/third_party/boringssl/crypto/x509/x509_test.cc:712:10: error: declaration of ‘struct X509Test_ZeroLengthsWithX509PARAM_Test::TestBody()::Test’ shadows a previous local [-Werror=shadow]
   struct Test {
          ^~~~
In file included from /home/kahou/katran/deps/grpc/third_party/boringssl/crypto/x509/x509_test.cc:19:
/home/kahou/katran/deps/grpc/third_party/boringssl/third_party/googletest/include/gtest/gtest.h:375:23: note: shadowed declaration is here
 class GTEST_API_ Test {
                       ^
cc1plus: all warnings being treated as errors
make[2]: *** [third_party/boringssl/crypto/CMakeFiles/crypto_test.dir/build.make:635: third_party/boringssl/crypto/CMakeFiles/crypto_test.dir/x509/x509_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2348: third_party/boringssl/crypto/CMakeFiles/crypto_test.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by tehnerd** [comment]
it is in external dependency. Let me see if Travis build is going to fail (approx in 4h. We run it once per day). Mb around that time grpc would be fixed. Last successful build
Was 18h ago so if there is an issue - it was recently introduced

**Comment by tehnerd** [comment]
I’m looking into Travis build which was running 2h ago and it compiles with no issues. Could you share lease try to rerun. If it still fails - paste the whole output + on which host (os version etc) you are building

**Comment by kahou82** [comment]
ok, let me compile it again and dump the output. My os version is

`Linux kahou 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kahou82** [comment]
@tehnerd output is in this link:

https://gist.github.com/kahou82/56a502b0c27557225da2c536c85c3a3f

**Comment by kahou82** [comment]
@tehnerd just want to let you know ubuntu 18.04 pass but ubuntu 18.10 fail.

Below is the os version that pass:

`Linux kahou 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by tehnerd** [comment]
well it looks like that boringssl cannot be build under gcc 8.2 (ubuntu 18.04 has 7.x; 18.10 comes with 8.2). you can follow up w/ em on "when they are planning to support 8.x" or you can fallback to 18.04 for building and run compiled binary on 18.10

**Comment by kahou82** [comment]
Ok, I can live with 18.04 for now. Thanks!

**Comment by tehnerd** [comment]
https://github.com/grpc/grpc/issues/16675
