### ISSUE TITLE
Typo in example?

### ISSUE THREAD

**Issue by kahou82** [facebookincubator/katran#28]
I am following the example of https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md and under Configuration of forwarding plane section step 4:

VIP must be configured on the **real**
$ sudo ip a a 10.200.200.1/32 dev lo

Should the VIP is on the server instead of the real?

**Comment by tehnerd** [comment]
No. Katran works in DSR mode (direct service return). So each real would terminate tcp session and reply to the user directly - hence it needs VIP to be configured

**Comment by tehnerd** [comment]
If you have any other questions - please feel free to reopen
