### ISSUE TITLE
libbpf: Error loading BTF: Invalid argument(22)

### ISSUE THREAD

**Issue by 4qv907rtet5r** [facebookincubator/katran#31]
HI
I got some ERRORs.
any suggestion?

~/katran# ./build/example_grpc/katran_server_grpc -balancer_prog ./deps/bpfprog/bpf/balancer_kern.o -default_mac 52:54:00:12:35:02 -forwarding_cores=0 -healthchecker_prog ./deps/bpfprog/bpf/healthchecking_ipip.o -intf=eth0 -ipip_intf=ipip0 -ipip6_intf=ipip60 -lru_size=10000

```
I0423 05:13:18.267051  8437 KatranGrpcService.cpp:67] Starting Katran
libbpf: Error loading BTF: Invalid argument(22)
libbpf: Error finalizing and loading .BTF into kernel: -22. Ignored and continue.
libbpf: Error loading BTF: Invalid argument(22)
libbpf: Error finalizing and loading .BTF into kernel: -22. Ignored and continue.
E0423 05:13:18.308995  8437 BpfLoader.cpp:87] Can't find map w/ name: lpm_src_v4
E0423 05:13:18.310480  8437 BpfLoader.cpp:87] Can't find map w/ name: decap_dst
Server listening on 0.0.0.0:50051
^CI0423 05:13:20.733433  8438 GrpcSignalHandler.cpp:37] Signal: 2, stopping service in 10000 milliseconds.
I0423 05:13:30.743686  8438 GrpcSignalHandler.cpp:42] Stopping Katran!
```

**Comment by tehnerd** [comment]
That means that kernel you are running at does not supports BTF yet. As messages says katran is ignoring it and continue to load. BTF is optional and katran perfectly works without it

**Comment by 4qv907rtet5r** [comment]
How do I get a kernel that supports BTF?

**Comment by tehnerd** [comment]
The same way you get your current one::
Either wait till your Linux distributive of choice starts to ship with something like 5.0+’kernel. Or build it by yourself

**Comment by 4qv907rtet5r** [comment]
It is too difficult to test.

Can you provide a test environment with vagrant?

**Comment by tehnerd** [comment]
Right now we don’t have anything like this. We will think about adding it (but not in nearest feature). What exactly do you find hard? We could try to improve our documentation so it would be more straight forward

**Comment by 4qv907rtet5r** [comment]
I created three vagrant VMs for testing.

- client
- katran
- server

It is not clear exactly what kind of VM should be set up.
(katran side : something...
server side : something...)

I'd like to have a vagrant that works well already.

I am following EXAMPLE.md and it does not work.

Sorry about my poor english.

**Comment by tehnerd** [comment]
What exactly doesn’t work in EXAMPLE? On what step you are having issue?

**Comment by 4qv907rtet5r** [comment]
Can we talk in irc or slack?

**Comment by tehnerd** [comment]
I’d prefer something less synchronous (as we are in different time zones). IMO github’s issues should work good enough.

**Comment by dankamongmen** [comment]
It might not be that your kernel is too old, but just that you need CONFIG_DEBUG_INFO_BTF=y.
