### ISSUE TITLE
Include port in real definition

### ISSUE THREAD

**Issue by jprukner** [facebookincubator/katran#38]
Hello, I'd like to make it possible to redirect packets to the port other than vip's port.
eg:
user --> katran(192.168.0.42:80) --> ... --> real(10.0.0.2:8080)

Could you please provide me a high level guide what needs to be changed in order to make it work? I will try to implement it.

**Comment by tehnerd** [comment]
katran is using ipip encapsulation as a way to deliver packets to reals. it does not modify original packets. so no, it is not possible to override ports.

**Comment by tehnerd** [comment]
the reason behind this is that katran works in DSR mode (when real replies to user directly and katran handling only ingress packets). overriding ports to something else would require for egress packets to be processed by katran as well - which is not supported today. probably you could use IPVS instead

**Comment by jprukner** [comment]
Oh, I see. Thanks.
