### ISSUE TITLE
travis is broken

### ISSUE THREAD

**Issue by tehnerd** [facebookincubator/katran#44]
is it a requirements for .travis.yml to be the way it is right now for ship-it/import-it to work? right now, because of this, travis make no sense and all PR/scheduled build are red. could we (at least temporary, till fbbuild would be able to work w/ katran) return to previous version of it?

**Comment by udippant** [comment]
Apologies for the noise. We're working to get the issues with ship-it resolved. We'll update on that soon.

**Comment by udippant** [comment]
This is resolved now: https://travis-ci.org/facebookincubator/katran/builds/592792022?utm_source=github_status&utm_medium=notification&fbclid=IwAR22W9e1PDgLDq3r4XhzQeijwQZOtG3Rp3uoUx1YyN81CqYJC46CmRhvpBc with commit https://github.com/facebookincubator/katran/commit/ac20ad02b0203f10a5d4246075cce4cd25847007

**Comment by udippant** [comment]
Kudos to @xubonnie  - it's finally happening :)

**Comment by tehnerd** [comment]
Thanks a lot @xubonnie
