### ISSUE TITLE
healthcheck problem

### ISSUE THREAD

**Issue by liayusuke** [facebookincubator/katran#47]
Hi， my config is similar to this one [about healthcheck](https://github.com/facebookincubator/katran/issues/45)  while for some reason in our cvm environment,  we modified balance_kern.c, DSR is replaced by TUNNEL and return packet will go through LB.

now packet forwarding is well but health check is not. Actually i can capture hc return packet  with tcpdump, but the hc process do not get the response.

configure in my environment

LB（katran）:

- eth0    172.33.4.100  --intf
- eth0:1 172.33.4.75    for tunnel back
- eth0:2 172.33.4.78    vip
- lo                             --hc_intf
- ipip0                        --ipip_intf

RS: 
configured with tunnel back
-eth0   172.33.35.7 mark 10000

health check program:
bind socket with 172.33.4.100 and send SYNC to 172.33.4.78(vip) with mark 10000.

for test, i modified balancer_kern, when recving IPIP pacekt, directly return XDP_PASS to kernel.

but my hc program do not recv ACK while i can capture ACK packet in LB with tcpdump.

strangely  when  i ifconfig down the vip in LB, hc program can recv ACK.

**Comment by tehnerd** [comment]
You  most likely has rp_filter sysctl enabled and because of this packets with vip as a src dropped from eth0 (as they don’t pass rp_filter check with vip configured on lo). In general if you see packets in tcpdump - then it has passed xdp (as xdp works before tcpdump)

**Comment by liayusuke** [comment]
Finally found beside rp_filter,  accept_local should be open too, thanks for you advice

**Comment by bienkma** [comment]
Hi @liayusuke  and @tehnerd,
I'm testing health check with my katran server where:
- katran:
  + interface: ens1f0 floating IP (exabgp); VIP: 203.205.x1.y1/25; real_ip for xabgp: 203.205.z1.k1/26
  + katran run with -hc_forwarding=true -healthchecker_prog ./deps/bpfprog/bpf/healthchecking_ipip.o option
- Real server 1:
  + interface 203.205.x2.y2/25
  + lo:0 203.205.x1.y1/25
  + ipip0: 127.0.0.42/32
  + nginx port 80
 - Real server 2:
  + interface 203.205.x3.y3/25
  + lo:0 203.205.x1.y1/25
  + ipip0: 127.0.0.42/32
  + nginx port 80
 Katran Loadbalancing the request from client to the real server as expectation. Exceptionally, katran didn't auto remove the real server in the loadbalancing when I stop nginx on realserver 2. Some requests to http://VIP still connection timeout. I followed the guide to do healthcheck https://github.com/facebookincubator/katran/blob/main/EXAMPLE.md

Why katran can't implement healthcheck as haproxy or keepalived for Loadbalancing. Could you help me to debug this case. Thank you!

**Comment by tehnerd** [comment]
this is a library. not a fully made service. it is implementing the way to forward healtchecks. but it does not actually implement any way to run them (it is up to user of the library how to implement them). so it is up to you how to do healtchecks and send them. katran library would help you to do ipip encapsulation if your healthcheck has proper somark.

as for why it does not implement: grpc server is an example of how this library could be used. not a final product.

also please create a new issue instead of posting in old one. FB folks, who owns this library, probably do not monitor closed issues, nor get notified that someone asked anything there
