### ISSUE TITLE
katran logo

### ISSUE THREAD

**Issue by brendangregg** [facebookincubator/katran#55]
Needs a logo (I'm building a slide of BPF technologies).

**Comment by yangchi** [comment]
What's the timeline? It may take some time.

**Comment by yangchi** [comment]
The design team responded with a 5 week timeline. Would that work?

**Comment by brendangregg** [comment]
That'll miss two talks (UbuntuMasters and re:Invent), but it'll make it in time for my 2020 talks!

A good logo will be worth it, so I wouldn't rush just because of those talks. There will be more. Thanks!

**Comment by brendangregg** [comment]
oh, and I'll be mentioning it in the meantime anyway, just using the name Katran.

**Comment by udippant** [comment]
https://github.com/facebookincubator/katran/commit/ff06eb088122380f1918a34815aa28f5a5ffdb20 adds logo for Katran (see logo.png in the root). Thanks for suggesting.
