### ISSUE TITLE
hc_it_client.py no found!

### ISSUE THREAD

**Issue by zhangyigui** [facebookincubator/katran#6]
HI, the recent study of your project kartan, I installed in the test environment, according to your EXAMPLE.md file, I find the source code did not find hc_it_client.py, you can provide this file. Thank you！

**Comment by tehnerd** [comment]
Sure. Most likele will just update documentation with src code of the script as it’s super simple

**Comment by tehnerd** [comment]
i've added source of this script in EXAMPLE.md with this commit: https://github.com/facebookincubator/katran/commit/8ad24d79377d725a6864c027d26eaf8301d0352a
