### ISSUE TITLE
Failed to build with build_katran.sh

### ISSUE THREAD

**Issue by junhosuh** [facebookincubator/katran#69]
Hi,

I am trying to build Katran with the latest commit `23add38cf9839b2bacafbf7330767853f69c3810` and Ubuntu 18.04, but it is failed due to the linkage error below. This is also the same issue Travis CI build has encountered.

> Scanning dependencies of target katran_server_grpc
[ 98%] Building CXX object example_grpc/CMakeFiles/katran_server_grpc.dir/katran_server.cpp.o
[100%] Linking CXX executable katran_server_grpc
../../deps/grpc/build/libgpr.a(host_port.cc.o): In function `grpc_core::(anonymous namespace)::DoSplitHostPort(absl::string_view, absl::string_view*, absl::string_view*, bool*)':
/home/ubuntu/workspace/katran/_build/deps/grpc/src/core/lib/gprpp/host_port.cc:77: undefined reference to `absl::string_view::find(char, unsigned long) const'
/home/ubuntu/workspace/katran/_build/deps/grpc/src/core/lib/gprpp/host_port.cc:79: undefined reference to `absl::string_view::find(char, unsigned long) const'
/home/ubuntu/workspace/katran/_build/deps/grpc/src/core/lib/gprpp/host_port.cc:53: undefined reference to `absl::string_view::find(char, unsigned long) const'
/home/ubuntu/workspace/katran/_build/deps/grpc/src/core/lib/gprpp/host_port.cc:70: undefined reference to `absl::string_view::find(char, unsigned long) const'
../../deps/grpc/build/libgpr.a(host_port.cc.o): In function `grpc_core::(anonymous namespace)::DoSplitHostPort(absl::string_view, absl::string_view*, absl::string_view*, bool*)':
/home/ubuntu/workspace/katran/_build/deps/grpc/third_party/abseil-cpp/absl/strings/string_view.h:382: undefined reference to `absl::base_internal::ThrowStdOutOfRange(char const*)'
collect2: error: ld returned 1 exit status
example_grpc/CMakeFiles/katran_server_grpc.dir/build.make:154: recipe for target 'example_grpc/katran_server_grpc' failed
make[2]: *** [example_grpc/katran_server_grpc] Error 1
CMakeFiles/Makefile2:2101: recipe for target 'example_grpc/CMakeFiles/katran_server_grpc.dir/all' failed
make[1]: *** [example_grpc/CMakeFiles/katran_server_grpc.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by udippant** [comment]
It looks like this commit in grpc https://github.com/grpc/grpc/commit/5207eba9ff30c19abeb923a7e040848177b59c01 broke the build. We'll likely need to pull in `absl`.
We'll try to get this dependency issue resolved. Meanwhile, as a temporary workaround, you can try using gprc release without this commit (https://github.com/grpc/grpc/releases).

**Comment by tehnerd** [comment]
@udippant  it seems that grpc starts to depends on absl (it is already installed by build_katran.sh) the only missing part is that linker does not know how to find absl libs. something like this should helps: https://gist.github.com/tehnerd/4e4f262ff88d6b40eeac3a68ee91254a but most likely it would break fb_builder (or w/e the name is as afair it has pinned version of grpc)

**Comment by udippant** [comment]
Ah yes, by virtue of `git submodule init` it is indeed pulled in as well. Linking with ABSL targets does indeed resolve the issue locally for me as well (fix coming).

**Comment by udippant** [comment]
Travis build passes after my latest commit. 
@junhosuh this should also fix this issue you are seeing. Let us know if it doesn't.

**Comment by junhosuh** [comment]
thx~

It seems fixed.
