### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by ttulttul** [facebookincubator/katran#70]
Hi, and sorry in advance for being naive. I have an interesting application for Katran and was wondering if you could let me know whether you think Katran would be a good fit.

I need to collect and encapsulate packets relating to TCP sessions which may be received at any of a number of distinct geographically distributed egress points from a large IP network. Packets returning from the internet relating to a particular TCP session may appear at any of a number of different edge routers.

I'm wondering if I could install Katran in each egress data center and configure it to encapsulate each TCP session and route it to a consistent server within a centralized cluster of processing servers somewhere inside the network. In reality, the centralized cluster is itself a TCP-to-TCP proxy that understands the relevant L7 protocol; however, we only need Katran to help with marshalling the packets from the edge. Once we're inside the network, the network's fabric can route packets properly to their destination from the filtering servers.

It seems like this should be possible because from Katran's point of view, whether Katran is literally at the "top of the rack" or in a completely different rack somewhere else in the world should make no difference. Note that latency here is not a real concern given the underlying protocol we are proxying.

**Comment by udippant** [comment]
>  I'm wondering if I could install Katran in each egress data center and configure it to encapsulate each TCP session and route it to a consistent server within a centralized cluster of processing servers somewhere inside the network 

From the limited context here, yes you should be able to setup Katran to do so. You can find setup tutorials at -  
https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md

**Comment by ttulttul** [comment]
Sorry for the limited context. The application itself is classified, unfortunately.

**Comment by udippant** [comment]
Feel free to re-open if you have more questions.
