### ISSUE TITLE
xdp-balancer not found

### ISSUE THREAD

**Issue by slabastrou** [facebookincubator/katran#76]
root@katran-big:/home/syla/katran# ./os_run_tester.sh 
+ '[' -z '' ']'
++ pwd
+ KATRAN_BUILD_DIR=/home/syla/katran/_build/build
+ '[' -z '' ']'
++ pwd
+ DEPS_DIR=/home/syla/katran/_build/deps
+ sudo sh -c '/home/syla/katran/_build/build/katran/lib/testing/katran_tester -balancer_prog /home/syla/katran/_build/deps/bpfprog/bpf/balancer_kern.o -test_from_fixtures=true '
libbpf: Error loading ELF section .BTF: -22.
E0212 21:58:01.396488  1322 BpfLoader.cpp:97] Can't find prog with name: xdp-balancer
terminate called after throwing an instance of 'std::invalid_argument'
  what():  can't get fd for prog: xdp-balancer, error: Invalid argument
Aborted (core dumped)

**Comment by udippant** [comment]
Did the script to build (https://github.com/facebookincubator/katran/blob/master/build_katran.sh) run successfully including the `build_bpf_modules_opensource .sh` https://github.com/facebookincubator/katran/blob/master/build_katran.sh#L460 ?

**Comment by slabastrou** [comment]
I am deploying an a fresh Ubuntu 18.04 Server VM (with latest upgrades) and I am able to fully compile (build_kratran and build_bpf) without errors. I can confirm that If I don't execute build_bpf, it fails. We also saw some occurence where restarting katran will fail until I execute build_bpf_... again.

So. looks like build_bpf must be executed manually before execution.

**Comment by slabastrou** [comment]
I tried in a different instance and even after executing build_bpf, it still fails. Looks like something somehow random.
