### ISSUE TITLE
Repo General Questions

### ISSUE THREAD

**Issue by ryanohnemus** [facebookincubator/katran#83]
I've been playing around with the katran library for a few days now and I was curious about the following things:

1) The repo (once built) includes fully functioning example servers. Is there a reason these haven't been moved from "examples" to just top level apps provided as a full L4 load balancing solutions within this repo? (By that I mean something like moving example_grpc to just be the standard provided katran server.) 

2) Since these are only examples right now, is it advised to only take these and use them in a library form / for testing and users should always be building their own full server using the katran lib?

3) I made a simple prometheus metrics exporter for the example_grpc server, is this something that you would want added to this repo?

4) Do you have any examples of how to create a pcap after you have built with KATRAN_INTROSPECTION enabled?

**Comment by udippant** [comment]
We are glad you found the examples useful. Per your questions:

1. We did intend these 'examples' to provide features necessary for a fully functioning L4 LB. Perhaps we could rename the 'example' and 'example_grpc' to 'thrift_server' and 'grpc_server' respectively :). 

2. Yes, you can use them in any form that works for you.  One typical setup is to spin the katran sever on its own, and run another process that periodically refreshes your configuration (for example healthchecks for backend servers) and updates the states appropriately via thrift / grpc calls. In this case, you do not need to make too much of the change on the katran server side.

3. We're usually hesitant to introduce new dependency on 3rd part for optional features. Having said that, you are always welcome to submit a PR for more specific discussions. We can at least add an example writeup section for users interested in integrating with prometheus.
 
4. It appears that we didn't merge the hook to trigger this via thrift / grpc calls to the open-source repo. We'll do that shortly. Meanwhile, here's the trigger: https://github.com/facebookincubator/katran/blob/master/katran/lib/KatranLb.cpp#L1062

**Comment by ryanohnemus** [comment]
Thank you @udippant! 

I'd definitely put in my vote to rename the servers as `thrift_server` and `grpc_server`. It just gives it more of a polished/complete feeling when you deploy something that isn't prefixed w/ the word 'example' :). Either way you guys go, i'll keep using it, with the word example in it or not :).

I understand the point on 3rd party integrations. It sounds like the best route would just be for me to create my own repo for the metric exporter and then I can send your team a link. If you find it interesting you could always link to any 3rd party stuff in a small section in the readme.

Thank you for the KatranMonitor link. I was trying to read through old issues/pull requests and saw at one point there was a 20 bpf instruction hit by using introspection. Does that happen only while a KatranMonitor is active (at runtime) or do you always have that perf hit if it is compiled with introspection?

**Comment by udippant** [comment]
Sorry for the late response. We'll follow on some of these changes in the next few weeks.

**Comment by linecolumn** [comment]
Just arrived, sorry if this is too noob question.

Katran is L4 LB, shouldn't it just do LB on port, and not on protocol? While here, is there example_http/s around sitting? :1234:

**Comment by udippant** [comment]
See https://github.com/facebookincubator/katran/tree/master/example for an example of a thrift service and https://github.com/facebookincubator/katran/tree/master/example_grpc for a grpc service to run Katran.

> Katran is L4 LB, shouldn't it just do LB on port, and not on protocol? 

I am assuming that you're suggesting that Katran should do load balancing *only* based on ports. While there may be some specific sub cases that may benefit, I don't see why this would be a good idea at a generic level. As a starter, this can lead to a skewed distribution of load among the backend servers since this would effectively result in load-balancing just based on the src port (as the dst port is mosly 443, 80).

**Comment by gsalisbury** [comment]
@ryanohnemus I would be interested in running the metric exporter, do you have a link to a repo you can share?

**Comment by RuchiSaluja8** [comment]
> Katran is L4 LB, shouldn't it just do LB on port, and not on protocol? While here, is there example_http/s around sitting?

@linecolumn check out the last section in this link : https://www.nginx.com/resources/glossary/layer-4-load-balancing/
While we call it L4LB, it is actually an L3/4LB - because the load balancer bases its decision on both the IP addresses of the origin and destination servers (Layer 3) and the TCP port number of the applications (Layer 4).
