### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by Phara0h** [facebookincubator/katran#87]
Good day, I was wondering if you could add some benchmarks that includes throughput and requests a second (or packets per second) at various level of concurrency with a single node. Bonus if the benchmark compares it's results to other layer 4 load balancers to get relative speed differences

**Comment by jdryan** [comment]
The `perf_testing` and `repeat` flags to katran_tester can be used for performance testing in isolation, though there is no support for changing concurrency.
