### ISSUE TITLE
./build_katran.sh error

### ISSUE THREAD

**Issue by kruztw** [facebookincubator/katran#93]
![err1](https://user-images.githubusercontent.com/38398190/89630293-bb475480-d8d1-11ea-8f64-f86e881423b4.PNG)

uname -a
Linux kruztw 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

**Comment by lnicco** [comment]
thanks for reporting. 
we are seeing this error with other opensource projects as well. 
Looking into it

**Comment by lnicco** [comment]
the problem with the folly build is that build_katran.sh tries to force everything to build with the `gnu++14` c++ flavor https://github.com/facebookincubator/katran/blob/master/build_katran.sh#L421

I'm going to post a diff to remove that constraint, or bump it to `gnu++17`

**Comment by lnicco** [comment]
@kruztw please let us know whether it is fixed on your side. 
I tested on Ubuntu 18.04.4 and it worked fine

**Comment by kruztw** [comment]
@lnicco Everything works find.
Thank you.
