### ISSUE TITLE
can't load main bpf program run os_run_tester.sh

### ISSUE THREAD

**Issue by bulelxq** [facebookincubator/katran#99]
I get this error when I run os_run_tester.sh
```
+ '[' -z '' ']'
++ pwd
+ KATRAN_BUILD_DIR=/home/bule/katran/_build/build
+ '[' -z '' ']'
++ pwd
+ DEPS_DIR=/home/bule/katran/_build/deps
+ sudo sh -c '/home/bule/katran/_build/build/katran/lib/testing/katran_tester -balancer_prog /home/bule/katran/_build/deps/bpfprog/bpf/balancer_kern.o -test_from_fixtures=true '
[sudo] password for bule:
libbpf: elf: skipping unrecognized data section(6) .maps.ctl_array
libbpf: elf: skipping unrecognized data section(7) .maps.vip_map
libbpf: elf: skipping unrecognized data section(8) .maps.fallback_cache
libbpf: elf: skipping unrecognized data section(9) .maps.ch_rings
libbpf: elf: skipping unrecognized data section(10) .maps.reals
libbpf: elf: skipping unrecognized data section(11) .maps.reals_stats
libbpf: elf: skipping unrecognized data section(12) .maps.stats
libbpf: elf: skipping unrecognized data section(13) .maps.quic_mapping
libbpf: elf: skipping unrecognized data section(25) .eh_frame
libbpf: elf: skipping relo section(26) .rel.eh_frame for section(25) .eh_frame
libbpf: load bpf program failed: Invalid argument
libbpf: failed to load program 'balancer_ingress'
libbpf: failed to load object '/home/bule/katran/_build/deps/bpfprog/bpf/balancer_kern.o'
E0922 09:58:04.089079  1681 BpfLoader.cpp:307] error while trying to load bpf object: /home/bule/katran/_build/deps/bpfprog/bpf/balancer_kern.o
terminate called after throwing an instance of 'std::invalid_argument'
  what():  can't load main bpf program
Aborted (core dumped)
```
ubuntu 18.04 and kernel 4.15

**Comment by tehnerd** [comment]
looks like latest libbpf is not compatible w/ 4.15 kernel. cc @udippant

**Comment by udippant** [comment]
Does the build succeed prior to the PR https://github.com/facebookincubator/katran/pull/96 (i.e. without `bpf_program__section_name`)?

**Comment by tehnerd** [comment]
Not the topic starter. But in my case it was failing. I thought that it was because behavior of prog title was changed. But no. I will try to bisect this today/tomorrow

**Comment by tehnerd** [comment]
so this one broke libbpf for 4.15: https://github.com/libbpf/libbpf/commit/a290d45322881d3b3fd1e972d0ca208c0b1c058a , prior commit works for katran (w/o #96 as it is using section_name; which was just recently introduced)

**Comment by tehnerd** [comment]
so the issue is that patch above starts to set attach_type unconditionally for xdp programs. and it does not work/supported by 4.15 kernel. quic fix like this one

**Comment by tehnerd** [comment]
```
diff --git a/katran/lib/BpfLoader.cpp b/katran/lib/BpfLoader.cpp
index dce5c8b..db37515 100644
--- a/katran/lib/BpfLoader.cpp
+++ b/katran/lib/BpfLoader.cpp
@@ -270,6 +270,7 @@ int BpfLoader::loadBpfObject(
                  << ::bpf_program__section_name(prog);
       return closeBpfObject(obj);
     }
+    bpf_program__set_expected_attach_type(prog, BPF_CGROUP_INET_INGRESS);
     auto prog_type = normalizeBpfProgType(prog, type);
     ::bpf_program__set_type(prog, prog_type);
   }
```
solve the issue (BPF_CGROUP_INET_INGRESS is equal to 0 in enum). but long term libbpf needs to be modified. 



but this one brings bigger question (i will open a ISSUE for that) - what is the FB's policy on kernel support

**Comment by udippant** [comment]
We might be able to resolve this by using specific release tag of the libbpf (instead of just cloning the repo, which is what the `build_katran.sh` script does) and guarding it behind kernel versions. That'll allow newer kernel to use the newer kernel versions while still making it compatible for the older kernel versions.

The other build flavor has the opposite problem, where the newer feature introduced in the #PR96 isn't present in the libbpf it pulls in.

**Comment by udippant** [comment]
FYI - the fix for this issue on the libbpf is on its way (by Andrii).

**Comment by udippant** [comment]
The fix in the kernel for this issue has now been merged into the libbpf repo https://github.com/libbpf/libbpf/commit/37c5973bb72237d5cf7a77da5078b7ff45fd62b8 , which should fix this issue.

**Comment by bulelxq** [comment]
I recompiled libbpf and katran.   Now run ./os_run_tester.sh have those errors.
```
I0925 10:32:28.344146 24344 BpfTester.cpp:220] Test: QUIC: short header w/ connection id but non-existing mapping. CIDv2 result: Passed
I0925 10:32:28.344154 24344 katran_tester.cpp:257] Testing counter's sanity. Printing on errors only
I0925 10:32:28.344367 24344 katran_tester.cpp:325] Testing of counters is complete
E0925 10:32:28.344594 24344 KatranSimulator.cpp:168] src and dst must have same address family
E0925 10:32:28.344609 24344 KatranSimulator.cpp:161] malformed src or dst ip address. src: aaaa dst: bbbb
E0925 10:32:28.344630 24344 BpfLoader.cpp:97] Can't find prog with name: cls-hc
I0925 10:32:28.344637 24344 katran_tester.cpp:179] Healthchecking not enabled. Skipping HC related tests
```
And run start_katran_grpc_server.sh report those,
```
+ '[' '!' -f /sys/fs/bpf/jmp_enp0s3 ']'
+ echo 'Assuming enp0s3 exists. please change script to actual interface if it does not'
Assuming enp0s3 exists. please change script to actual interface if it does not
+ sudo sh -c '/home/bule/katran/_build/build/katran/lib/xdproot -bpfprog /home/bule/katran/_build/deps/bpfprog/bpf/xdp_root.o -bpfpath=/sys/fs/bpf/jmp_enp0s3 -intf=enp0s3'
libbpf: elf: skipping unrecognized data section(16) .eh_frame
libbpf: elf: skipping relo section(17) .rel.eh_frame for section(16) .eh_frame
can't detach xdp prog
```

**Comment by tehnerd** [comment]
Tests are passing. Some errors in output are expecting as there explicit tests that has incorrrect input values (to test that lib does not crash). As for grpc - looks like your system does not have enp0s3 interface and you need to modify script as recommended in output of the script

**Comment by bulelxq** [comment]
ok,thanks
